sudo: required

env:
 - DIST=lucid
 - DIST=precise
 - DIST=trusty

before_install:
  - cp -a .pbuilderrc $HOME
  - sudo apt-get update -qq
  - sudo apt-get install pbuilder aptitude
  - sudo pbuilder create --debootstrapopts --variant=buildd

script: sudo debuild-pbuilder -us -uc

os: linux
