language: cpp

compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install pbuilder
  - sudo pbuilder create --debootstrapopts --variant=buildd

script: sudo debuild-pbuilder -us -uc

os: linux
