sudo: required

env:
 - DIST=precise
 - DIST=trusty

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install pbuilder aptitude ubuntu-dev-tools libgsl0-dev libblas-dev
 - for CHAR in $(seq 0 9) a b c d e f; do sudo mkdir -p /var/cache/pbuilder/ccache/${CHAR}; done
 - pbuilder-dist ${DIST} create --debootstrapopts --variant=buildd
 - sudo pip install cpp-coveralls

script:
 - sed -i "s:precise:${DIST}:g" debian/changelog
 - debuild -S -uc
 - pbuilder-dist ${DIST} build ../*.dsc
# Rebuild so that coverage stats can be collected
 - sudo debuild-pbuilder -us -uc

after_success: coveralls --gcov-options '\-lp'

os: linux
