sudo: required

env:
 - DIST=lucid
 - DIST=precise
 - DIST=trusty

before_install:
 - cp -a .pbuilderrc $HOME
 - sudo apt-get update -qq
 - sudo apt-get install pbuilder aptitude
 - sudo apt-get install libgsl0-dev
 - sudo apt-get install libblas-dev
 - sudo pbuilder create --debootstrapopts --variant=buildd

install:
 - sudo pip install cpp-coveralls

script: sudo debuild-pbuilder -us -uc

after_success: coveralls --gcov-options '\-lp'

os: linux
